#!/bin/bash

tmpfile=$(mktemp ~/tmp/meeting.XXXXXXX)
dt=$(date +'%Y-%m-%d')

echo -n "Enter title: "
read title
title=$(echo $title | sed 's/mtg:/*MEETING:*/')
echo "### ($dt) $title" >> $tmpfile

echo -n "Enter meeting item: "
read meeting_item
meeting_item=$(echo $meeting_item | sed 's/ai:/*AI:*/')

echo "+ $meeting_item" >> $tmpfile

cat $tmpfile | cat - ~/journal/journal.markdown > temp && mv temp ~/journal/journal.markdown

